const FilterSize = () => {
  return (
    <div className="sidebar__brand sidebar__filter-container">
      <div className="sidebar__header-container">
        <h4 className="sidebar__header sidebar__brand-header sidebar__size-header">
          РАЗМЕР
        </h4>
        <button className="sidebar__button sidebar__button-dropdown"></button>
      </div>

      <div className="sidebar__form-wrapper sidebar__price-wrapper">
        <table>
          <tbody>
            <tr>
              <td>
                <button>35</button>
              </td>
              <td>
                <button>35.5</button>
              </td>
              <td>
                <button>36</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>36.5</button>
              </td>
              <td>
                <button>37</button>
              </td>
              <td>
                <button>37.5</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>38</button>
              </td>
              <td>
                <button>38.5</button>
              </td>
              <td>
                <button>39</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>39.5</button>
              </td>
              <td>
                <button>40</button>
              </td>
              <td>
                <button>40.5</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>41</button>
              </td>
              <td>
                <button>41.5</button>
              </td>
              <td>
                <button>42</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>42.5</button>
              </td>
              <td>
                <button>43</button>
              </td>
              <td>
                <button>43.5</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>44</button>
              </td>
              <td>
                <button>44.5</button>
              </td>
              <td>
                <button>45</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>45.5</button>
              </td>
              <td>
                <button>46</button>
              </td>
              <td>
                <button>46.5</button>
              </td>
            </tr>
            <tr>
              <td>
                <button>47</button>
              </td>
              <td>
                <button>47.5</button>
              </td>
              <td>
                <button>48</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default FilterSize;
